version: '1'
volumes:
  data:
services:
  # docker build -t c3-db ./db/ && docker build -t c3-api ./api/ && docker build -t c3-nginx ./nginx/
  # docker-compose down && docker-compose up
  db:
    # restart: always
    # build: ./db
    image: c3-db
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - data:/var/lib/mysql

  api:
    # build: ./api
    image: c3-api
    environment:
      - APP_PORT=8080 # ${APP_PORT}
      - DB_PORT=3306 # ${DB_PORT}
      - DB_USER=root # ${DB_USER}
      - DB_NAME=challenge3 # ${DB_NAME}
      - DB_PASSWORD=rootpassword # ${DB_PASSWORD}
    depends_on:
      - db
    deploy:
      # Scale testing for Docker Challenge #4
      replicas: 8

  nginx:
    # build: ./nginx
    image: c3-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
